### ISSUE TITLE
Vaillant calorMATC 350 question

### ISSUE THREAD

**Issue by luci84tm** [eBUS/adapter#1]
Hello there,

This is not an issue, but more a question about a possible setup.
I do have in my flat a Vaillant atmoTEC Plus with a wall thermostat calorMATC 350.
What kind of possibilities do I have to connect to the boiler:
- via eBUS adapter in parallel with the wall thermostat?
- via wall thermostat diagnose port ?
- or via eBUS adapter only, no wall thermostat would work in parallel

I'm interested in the second option, if I could still make use of the VRT 350 and use the diagnose port for controlling the heating system.
Would such a scenario be supported ?

**Comment by Reinhartd** [comment]
Hello, 

You have to connect the adapter parallel to the eBus and all devices stay as they are!
This is scenario one!

**Comment by john30** [comment]
diagnose port is not supported unless it is an eBUS as well. other than that, simply connect eBUS directly in parallel. thanks @Reinhartd for answering

**Comment by luci84tm** [comment]
Thanks allot for the prompt reply!!
What happens if one is changing some setting via wall thermostat and then another command via eBus is changing the same setting ?

**Comment by Reinhartd** [comment]
the last one wins!

**Comment by luci84tm** [comment]
One last question: where is the schedule stored, on the wall thermostat or on the heating system ?
If it is stored on the boiler, then is fine, if it is on the wall thermostat then what evere I set via eBUS the thermostat will change at next schedule.

**Comment by john30** [comment]
usually in the heater

**Comment by luci84tm** [comment]
I do have a short question:
from where can I order the base board?
or let me ask in a different way: can I order it from somewhere or I have to design it my self and find a supplier to print it for me?

**Comment by john30** [comment]
you can get it from me [here](https://forum.fhem.de/index.php/topic,93190.0.html), english posts are fine as well
