### ISSUE TITLE
Random periodical hang up of the ebus adapter

### ISSUE THREAD

**Issue by jordipalet** [eBUS/adapter#10]
I'm using the Ethernet version, with static IP address. It works well, but every few days it hangs up. I tried to debug it without any luck, I replaced 3 times the power adapter, with several ones that I know are good, no luck. The only thing that seems to work is to power cycle the ebus adapter *and* restart the ebusd service. I'm using it via domoticz, but the problem is not at the domoticz level, because using the scan/find commands still doesn't provide any results (even the http://xxxx:8889/data?def provides no data). Anyone got the same trouble? Any way to force an ebus adapter reboot periodically? Or hints about how to debug it? because the problem is that only happens every 1-2 weeks, sometimes after 3 weeks ...
By the way, the error I'm getting is "Error: ebus: (ebus) Error from telnet client: element not found" and the ebusd.log shows nothing related to that.

**Comment by john30** [comment]
which version of ebusd do you use and which version of the adapter firmware?
the error message does not seem to come from ebusd but from your integration. what does the ebusd.log file contain?
when the issue occurs again it would be good to stop ebusd, start a tcpdump for traffic to/from the adapter port 9999 and then start ebusd again.

**Comment by jordipalet** [comment]
ebusd 21.3.v21.3
How can I get the adapter firmware version? I've not updated it from what I got ...
The ebusd.log doesn't show anything compared with what is there when working normally ...

However, I believe I found the problem and not sure why it happens. It looks like always happen at 00:00, so I suspected it was related to logrotate.

When ebusd is installed, the logrotate contained

	postrotate
		invoke-rc.d ebusd restart > /dev/null
	endscript

I've replaced it with "#" in front of the 3 lines.

and it seems is no longer happening (after opening the issue it happened for 2 consecutive days until I modified the logrotate). I can only wait a few additional days/weeks to confirm that was the problem.

Does that make any sense to you?

**Comment by john30** [comment]
maybe you have more than one ebusd running, which could result in the described behaviour. please check by using e.g. "ps aux|grep ebusd" when the issue occurs

**Comment by jordipalet** [comment]
> maybe you have more than one ebusd running, which could result in the described behaviour. please check by using e.g. "ps aux|grep ebusd" when the issue occurs

confirmed, there is only one running ...

**Comment by john30** [comment]
I think I've found a potential issue with an unexpected state on the Ethernet module that might be related to this. please check with [new firmware 20220220](https://github.com/eBUS/adapter/blob/master/firmware/20220220-offset.hex)

**Comment by john30** [comment]
closed due to inactivity
