### ISSUE TITLE
fortschritt esphome

### ISSUE THREAD

**Issue by tilman** [eBUS/adapter#12]
Hab gerade in den Docs etwas zu esphome gelesen: https://github.com/eBUS/adapter/blob/master/wemosebus.md#esphome

Gibt es dazu schon einen fortschritt bzw. kann ich vielleicht beim testen oder weiterentwickeln unterstützen? Ich hab schon ein paar plugins für esphome geschrieben, würde mich also mit esphome an sich auskennen.

**Comment by john30** [comment]
this will be addressed with level 2 of enhanced protocol.
