### ISSUE TITLE
https://ebus.github.io/adapter/ is broken

### ISSUE THREAD

**Issue by eh-gh** [eBUS/adapter#15]
Hi,

the ebus adapter site for v2 is broken.
Could you please set it back / create a branch for this version?

tnx

eh-gh

**Comment by eh-gh** [comment]
more precisely:
the wiki page
https://github.com/eBUS/adapter
describes, that the info about v2 adapter can be reached via https://ebus.github.io/adapter/

I could reach it only via:
https://adapter.ebusd.eu/v2/index.en.html

**Comment by john30** [comment]
done in 41a858780b3676e57ac872d39793f05492406d22
