### ISSUE TITLE
Is it possible to buy somewhere eBUS adapter PCB?

### ISSUE THREAD

**Issue by komw** [eBUS/adapter#2]
As in subject, is it possible to buy somewhere this PCB? It would be great if it be possible to buy whole assembled circut. I've tried to find it on ebay, but there is only one offer with some very old version of PCB

**Comment by hvorragend** [comment]
Found this one today. Not mine. 
https://forum.fhem.de/index.php/topic,102956.msg976688.html#msg976688

**Comment by john30** [comment]
it weill be possible to get PCBs soon. details will be announced [here](https://forum.fhem.de/index.php?topic=75878.new;topicseen#new)

**Comment by john30** [comment]
orders can be placed now:
- [base and extension PCB](https://forum.fhem.de/index.php/topic,104268.0.html)
- [Raspberry Pi kit or ready-to-use](https://forum.fhem.de/index.php/topic,104259.0.html)

**Comment by tlc76** [comment]
Hi @john30, can you please advise if the PCBs are still available to order? I would desperately need two pieces and I missed the fhem.de forum conversation from October 2019...

Many thanks, 
Cristian

**Comment by ghosty-be** [comment]
Yeah I would also like to order the base board. I had it attached with a ebus to usb adapter from e-service to a raspberry pi running ebusd, but as my heater is on the attic it doesn't make much sense to run a seperate pi only for that on the attic (I have another one which is directly connected to gas/water/electricity in the garage 2 floors down...). As far as I understand the base board + a wemos d1 is enough to just signal stuff to wifi and then I can just install ebusd on the pi in the garage...
Or can you give the gerber file so we can send them to jlcpcb or similar service to get them manufactured ourselves?

**Comment by john30** [comment]
please subscribe to the boards on fhem

**Comment by garageboxnv** [comment]
Over the past 1.5 years on multiple occasions I tried to create an account on fhem to be able to subscribe and order an adapter plate.
I'm still unsuccesfull is there any alternative option to order the adapter plate?

**Comment by john30** [comment]
you can reserve it now here: [https://ebusd.eu/myadapter/](https://ebusd.eu/myadapter/)

**Comment by nyxnyx** [comment]
hi, I've reserved my last week - any progress on collecting good batch to order?

**Comment by john30** [comment]
> hi, I've reserved my last week - any progress on collecting good batch to order?

due to the global chip crisis, we don't expect the next batch to be available before 2022

**Comment by fhackenberger** [comment]
As I was searching for an alternative, there's also a commercial one: [esera.de](https://www.esera.de/produkte/ebus/135/1-wire-hub-platine)

**Comment by ghosty-be** [comment]
> As I was searching for an alternative, there's also a commercial one: [esera.de](https://www.esera.de/produkte/ebus/135/1-wire-hub-platine)

I have that one, but next to the fact it was quite expensive vs the above DIY solution it still requires something to interface with towards network, as I have my boiler at the attic I plugged it into a zeroPI (chinese arm thing that has 1 USB and 1 wired network port) that runs armbian with ebusd... but I'd rather have a microcontroller like esp running the interfacing to network because these micro pcs and their SD card usually crash after a long time because the SD card wears out unfortunately :(

**Comment by cibernox** [comment]
@john30 do you have a rough estimation about when in 2022 that might be? Early 2022 hopefully? I also found about the eBuzzz adapter (https://www.tindie.com/products/foxrom/ebus-usb-adapter-ebuzzz-adapter) which is not mentioned in the wiki, does anyone know if it has latency issues like some others?

**Comment by john30** [comment]
one of the parts has an official lead time of 52 weeks. that's why we're looking for alternatives already

**Comment by john30** [comment]
> does anyone know if it has latency issues like some others?

to answer your question: every adapter not having a hardware doing the arbitration has the latency issue when writing to the bus. as long as you only want to listen to the traffic, that's no problem

**Comment by cibernox** [comment]
> to answer your question: every adapter not having a hardware doing the arbitration has the latency issue when writing to the bus. as long as you only want to listen to the traffic, that's no problem

Then it should not be a problem. I will write to the bus from time to time, but not in a critical time-constrained way, nor in a rapid sequence. If a message takes seconds or even a minute to be sent to the bus it's not a deal breaker.

Thanks!

**Comment by john30** [comment]
it is not a matter of how often you write to the bus, but just if you write at all. you'll create bus traffic that is not within the specs. depending on your heater this might be treated as "noise" on the bus but it might as well lead to misbehaviour of controlling units.
