### ISSUE TITLE
Can I use lm393 instead of tlc393?

### ISSUE THREAD

**Issue by dzikus** [eBUS/adapter#3]
I have builded 2.2 version by myself and I have only lm393, can I use it instead of tlc393?

Am I thinking right that SJ1 should be disconnected if I’m using dc-dc to power 78L05?

![489DEBB7-CA50-4440-BF98-0A23E9C5518D](https://user-images.githubusercontent.com/3209066/78471659-443b5d00-7733-11ea-8390-5607eed9a744.jpeg)

**Comment by john30** [comment]
I don't know if LM393 will do, you'll have to check the specs.
Yes, SJ1 needs to be disconnected when using DC-DC converter

**Comment by Chiuaua79** [comment]
@dzikus : did it work with LM393 or did you have to change to TLC393 afer all? Made a homebrew 2.2 version myself also with LM393, but the Wemos with ebus firmware from John did not recognise my adapter. Measurements are OK compared to the measurement plan, but it seems like RX does not get proper GND, where the comparator is not pulling the optocoupler fully down.

**Comment by dzikus** [comment]
It didn't work with LM393 and I didn't have time to test it with TLC393.

**Comment by john30** [comment]
closed for no longer relevant to the adapter 3
