### ISSUE TITLE
adapter + oem room controller

### ISSUE THREAD

**Issue by CzarlsOnGit** [eBUS/adapter#7]
Hi,
Is it possible to connect adapter an still have functionality of main OEM controler ?(in may case Sounier Duval EXACONTROL E 7 C- also based on ebus),
![image](https://user-images.githubusercontent.com/20352387/130971929-16a9d234-b70e-4405-9b83-59034ee9c4fd.png)

**Comment by john30** [comment]
sure, it is a bus anyway
