### ISSUE TITLE
Adapter 3 housing

### ISSUE THREAD

**Issue by nixmeer** [eBUS/adapter#9]
Hello :) 

I was looking for a raspberry pi case that fits the ebus adapter but found none. In order to create one, I was looking for any 3D model or EAGLE files so I could create one myself but couldn't find any of these either. I guess there are some 3D files since there are renderings on the website

Is the hardware open source as well or is it possible to get the files for that purpose? If there's any interest in the housing or the 3D files, I'd make them available as well.

best 

Jan

**Comment by john30** [comment]
there are some cases designed already, e.g. here:
* https://www.thingiverse.com/thing:4713754 from [chons](https://www.thingiverse.com/chons)
* https://www.thingiverse.com/thing:4698626 from [Fuso2001](https://www.thingiverse.com/Fuso2001)

**Comment by nixmeer** [comment]
I could not find one for the pi version that also houses the pi. Others on thing thingiverse are for the Ethernet, usb and wemos versions.

**Comment by Ashtray0** [comment]
I "built" one for the Raspberry Pi Zero. Not pretty, but works quite well :)

https://www.printables.com/de/model/254337-ebus-gehause

Maybe someone can use it.
